eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      # Örn. tek düğüm: http://eureka-server:8761/eureka/
      #      HA: http://eureka-1:8761/eureka/,http://eureka-2:8761/eureka/
      defaultZone: ${EUREKA_SERVER_ZONE:http://eureka-server:${server.port}/eureka/}
  server:
    # Ağ kesintilerinde kayıtların erken silinmesini önleyen koruma mekanizması.
    enable-self-preservation: true

logging:
  level:
    root: WARN
    com.etiya: INFO
